### ISSUE TITLE
生成mvc的时候报错了

### ISSUE THREAD

**Issue by TomYule** [enilu/nutzwk-plugin#3]
`"D:\Program Files\Java\jdk1.8.0_101\bin\java" -agentlib:jdwp=transport=dt_socket,address=127.0.0.1:56421,suspend=y,server=n -Dfile.encoding=UTF-8 -classpath "D:\Program Files\Java\jdk1.8.0_101\jre\lib\charsets.jar;D:\Program Files\Java\jdk1.8.0_101\jre\lib\deploy.jar;D:\Program Files\Java\jdk1.8.0_101\jre\lib\javaws.jar;D:\Program Files\Java\jdk1.8.0_101\jre\lib\jce.jar;D:\Program Files\Java\jdk1.8.0_101\jre\lib\jfr.jar;D:\Program Files\Java\jdk1.8.0_101\jre\lib\jfxswt.jar;D:\Program Files\Java\jdk1.8.0_101\jre\lib\jsse.jar;D:\Program Files\Java\jdk1.8.0_101\jre\lib\management-agent.jar;D:\Program Files\Java\jdk1.8.0_101\jre\lib\plugin.jar;D:\Program Files\Java\jdk1.8.0_101\jre\lib\resources.jar;D:\Program Files\Java\jdk1.8.0_101\jre\lib\rt.jar;D:\Program Files\Java\jdk1.8.0_101\jre\lib\ext\access-bridge-64.jar;D:\Program Files\Java\jdk1.8.0_101\jre\lib\ext\cldrdata.jar;D:\Program Files\Java\jdk1.8.0_101\jre\lib\ext\dnsns.jar;D:\Program Files\Java\jdk1.8.0_101\jre\lib\ext\jaccess.jar;D:\Program Files\Java\jdk1.8.0_101\jre\lib\ext\jfxrt.jar;D:\Program Files\Java\jdk1.8.0_101\jre\lib\ext\localedata.jar;D:\Program Files\Java\jdk1.8.0_101\jre\lib\ext\nashorn.jar;D:\Program Files\Java\jdk1.8.0_101\jre\lib\ext\sunec.jar;D:\Program Files\Java\jdk1.8.0_101\jre\lib\ext\sunjce_provider.jar;D:\Program Files\Java\jdk1.8.0_101\jre\lib\ext\sunmscapi.jar;D:\Program Files\Java\jdk1.8.0_101\jre\lib\ext\sunpkcs11.jar;D:\Program Files\Java\jdk1.8.0_101\jre\lib\ext\zipfs.jar;F:\ideaProject\newlook\target\classes;F:\apache-maven-3.3.9\repository\org\nutz\nutz-integration-quartz\1.r.56\nutz-integration-quartz-1.r.56.jar;F:\apache-maven-3.3.9\repository\org\quartz-scheduler\quartz\2.2.1\quartz-2.2.1.jar;F:\apache-maven-3.3.9\repository\org\slf4j\slf4j-api\1.6.6\slf4j-api-1.6.6.jar;F:\apache-maven-3.3.9\repository\org\nutz\nutz-integration-shiro\1.r.56\nutz-integration-shiro-1.r.56.jar;F:\apache-maven-3.3.9\repository\org\apache\shiro\shiro-web\1.2.3\shiro-web-1.2.3.jar;F:\apache-maven-3.3.9\repository\org\apache\shiro\shiro-core\1.2.3\shiro-core-1.2.3.jar;F:\apache-maven-3.3.9\repository\commons-beanutils\commons-beanutils\1.8.3\commons-beanutils-1.8.3.jar;F:\apache-maven-3.3.9\repository\commons-logging\commons-logging\1.1.1\commons-logging-1.1.1.jar;F:\apache-maven-3.3.9\repository\org\nutz\nutz\1.r.57\nutz-1.r.57.jar;F:\apache-maven-3.3.9\repository\org\nutz\nutz-web\1.r.57\nutz-web-1.r.57.jar;F:\apache-maven-3.3.9\repository\org\eclipse\jetty\aggregate\jetty-all-server\7.6.18.v20150929\jetty-all-server-7.6.18.v20150929.jar;F:\apache-maven-3.3.9\repository\org\eclipse\jetty\orbit\javax.servlet\2.5.0.v201103041518\javax.servlet-2.5.0.v201103041518.jar;F:\apache-maven-3.3.9\repository\org\eclipse\jetty\orbit\javax.security.auth.message\1.0.0.v201108011116\javax.security.auth.message-1.0.0.v201108011116.jar;F:\apache-maven-3.3.9\repository\org\eclipse\jetty\orbit\javax.mail.glassfish\1.4.1.v201005082020\javax.mail.glassfish-1.4.1.v201005082020.jar;F:\apache-maven-3.3.9\repository\org\eclipse\jetty\orbit\javax.activation\1.1.0.v201105071233\javax.activation-1.1.0.v201105071233.jar;F:\apache-maven-3.3.9\repository\org\eclipse\jetty\orbit\javax.annotation\1.1.0.v201108011116\javax.annotation-1.1.0.v201108011116.jar;F:\apache-maven-3.3.9\repository\org\eclipse\jetty\orbit\javax.servlet.jsp\2.1.0.v201105211820\javax.servlet.jsp-2.1.0.v201105211820.jar;F:\apache-maven-3.3.9\repository\org\eclipse\jetty\jetty-jsp\7.6.18.v20150929\jetty-jsp-7.6.18.v20150929.jar;F:\apache-maven-3.3.9\repository\org\eclipse\jetty\orbit\org.apache.jasper.glassfish\2.1.0.v201110031002\org.apache.jasper.glassfish-2.1.0.v201110031002.jar;F:\apache-maven-3.3.9\repository\org\eclipse\jetty\orbit\javax.servlet.jsp.jstl\1.2.0.v201105211821\javax.servlet.jsp.jstl-1.2.0.v201105211821.jar;F:\apache-maven-3.3.9\repository\org\eclipse\jetty\orbit\org.apache.taglibs.standard.glassfish\1.2.0.v201112081803\org.apache.taglibs.standard.glassfish-1.2.0.v201112081803.jar;F:\apache-maven-3.3.9\repository\org\eclipse\jetty\orbit\javax.el\2.1.0.v201105211819\javax.el-2.1.0.v201105211819.jar;F:\apache-maven-3.3.9\repository\org\eclipse\jetty\orbit\com.sun.el\1.0.0.v201105211818\com.sun.el-1.0.0.v201105211818.jar;F:\apache-maven-3.3.9\repository\org\eclipse\jetty\orbit\org.eclipse.jdt.core\3.7.1\org.eclipse.jdt.core-3.7.1.jar;F:\apache-maven-3.3.9\repository\log4j\log4j\1.2.17\log4j-1.2.17.jar;F:\apache-maven-3.3.9\repository\com\alibaba\druid\1.0.23\druid-1.0.23.jar;D:\Program Files\Java\jdk1.8.0_101\lib\jconsole.jar;D:\Program Files\Java\jdk1.8.0_101\lib\tools.jar;F:\apache-maven-3.3.9\repository\mysql\mysql-connector-java\5.1.39\mysql-connector-java-5.1.39.jar;F:\apache-maven-3.3.9\repository\jstl\jstl\1.2\jstl-1.2.jar;F:\apache-maven-3.3.9\repository\cn\enilu\tools\nutzwk-code-generator\1.1\nutzwk-code-generator-1.1.jar;F:\apache-maven-3.3.9\repository\org\atteo\evo-inflector\1.0.1\evo-inflector-1.0.1.jar;F:\apache-maven-3.3.9\repository\commons-cli\commons-cli\1.2\commons-cli-1.2.jar;F:\apache-maven-3.3.9\repository\org\apache\velocity\velocity\1.7\velocity-1.7.jar;F:\apache-maven-3.3.9\repository\commons-collections\commons-collections\3.2.1\commons-collections-3.2.1.jar;F:\apache-maven-3.3.9\repository\commons-lang\commons-lang\2.4\commons-lang-2.4.jar;E:\Program Files (x86)\JetBrains\IntelliJ IDEA 14.0.3\lib\idea_rt.jar" cn.enilu.common.code.Generator -i User -u /private/newlook -p com.newlook -v index_add_detail_edit_ controller service view
Connected to the target VM, address: '127.0.0.1:56421', transport: 'socket'
2016-08-24 17:05:27,898 [main] DEBUG org.nutz.resource.Scans - Locations for Scans:
[JarResourceLocation [jarPath=F:\apache-maven-3.3.9\repository\org\apache\shiro\shiro-core\1.2.3\shiro-core-1.2.3.jar], JarResourceLocation [jarPath=F:\apache-maven-3.3.9\repository\org\eclipse\jetty\orbit\javax.servlet.jsp\2.1.0.v201105211820\javax.servlet.jsp-2.1.0.v201105211820.jar], JarResourceLocation [jarPath=F:\apache-maven-3.3.9\repository\org\nutz\nutz-integration-shiro\1.r.56\nutz-integration-shiro-1.r.56.jar], JarResourceLocation [jarPath=F:\apache-maven-3.3.9\repository\org\nutz\nutz\1.r.57\nutz-1.r.57.jar], JarResourceLocation [jarPath=D:\Program Files\Java\jdk1.8.0_101\jre\lib\ext\sunjce_provider.jar], JarResourceLocation [jarPath=F:\apache-maven-3.3.9\repository\org\eclipse\jetty\orbit\javax.servlet\2.5.0.v201103041518\javax.servlet-2.5.0.v201103041518.jar], JarResourceLocation [jarPath=F:\apache-maven-3.3.9\repository\org\eclipse\jetty\orbit\org.eclipse.jdt.core\3.7.1\org.eclipse.jdt.core-3.7.1.jar], JarResourceLocation [jarPath=F:\apache-maven-3.3.9\repository\org\atteo\evo-inflector\1.0.1\evo-inflector-1.0.1.jar], JarResourceLocation [jarPath=D:\Program Files\Java\jdk1.8.0_101\jre\lib\ext\nashorn.jar], FileSystemResourceLocation [root=F:\ideaProject\newlook], JarResourceLocation [jarPath=F:\apache-maven-3.3.9\repository\commons-cli\commons-cli\1.2\commons-cli-1.2.jar], JarResourceLocation [jarPath=F:\apache-maven-3.3.9\repository\org\apache\shiro\shiro-web\1.2.3\shiro-web-1.2.3.jar], JarResourceLocation [jarPath=F:\apache-maven-3.3.9\repository\org\eclipse\jetty\orbit\javax.annotation\1.1.0.v201108011116\javax.annotation-1.1.0.v201108011116.jar], JarResourceLocation [jarPath=D:\Program Files\Java\jdk1.8.0_101\jre\lib\jfr.jar], JarResourceLocation [jarPath=D:\Program Files\Java\jdk1.8.0_101\jre\lib\resources.jar], JarResourceLocation [jarPath=D:\Program Files\Java\jdk1.8.0_101\jre\lib\deploy.jar], JarResourceLocation [jarPath=D:\Program Files\Java\jdk1.8.0_101\jre\lib\rt.jar], JarResourceLocation [jarPath=D:\Program Files\Java\jdk1.8.0_101\jre\lib\ext\sunmscapi.jar], JarResourceLocation [jarPath=F:\apache-maven-3.3.9\repository\org\eclipse\jetty\orbit\javax.activation\1.1.0.v201105071233\javax.activation-1.1.0.v201105071233.jar], JarResourceLocation [jarPath=F:\apache-maven-3.3.9\repository\org\eclipse\jetty\orbit\javax.el\2.1.0.v201105211819\javax.el-2.1.0.v201105211819.jar], JarResourceLocation [jarPath=F:\apache-maven-3.3.9\repository\org\eclipse\jetty\orbit\org.apache.jasper.glassfish\2.1.0.v201110031002\org.apache.jasper.glassfish-2.1.0.v201110031002.jar], JarResourceLocation [jarPath=D:\Program Files\Java\jdk1.8.0_101\lib\tools.jar], JarResourceLocation [jarPath=F:\apache-maven-3.3.9\repository\mysql\mysql-connector-java\5.1.39\mysql-connector-java-5.1.39.jar], JarResourceLocation [jarPath=F:\apache-maven-3.3.9\repository\commons-collections\commons-collections\3.2.1\commons-collections-3.2.1.jar], JarResourceLocation [jarPath=F:\apache-maven-3.3.9\repository\com\alibaba\druid\1.0.23\druid-1.0.23.jar], JarResourceLocation [jarPath=F:\apache-maven-3.3.9\repository\org\apache\velocity\velocity\1.7\velocity-1.7.jar], JarResourceLocation [jarPath=F:\apache-maven-3.3.9\repository\org\eclipse\jetty\orbit\javax.security.auth.message\1.0.0.v201108011116\javax.security.auth.message-1.0.0.v201108011116.jar], JarResourceLocation [jarPath=F:\apache-maven-3.3.9\repository\commons-lang\commons-lang\2.4\commons-lang-2.4.jar], JarResourceLocation [jarPath=D:\Program Files\Java\jdk1.8.0_101\jre\lib\ext\cldrdata.jar], JarResourceLocation [jarPath=D:\Program Files\Java\jdk1.8.0_101\jre\lib\ext\dnsns.jar], JarResourceLocation [jarPath=D:\Program Files\Java\jdk1.8.0_101\jre\lib\jsse.jar], JarResourceLocation [jarPath=D:\Program Files\Java\jdk1.8.0_101\jre\lib\charsets.jar], JarResourceLocation [jarPath=F:\apache-maven-3.3.9\repository\org\nutz\nutz-integration-quartz\1.r.56\nutz-integration-quartz-1.r.56.jar], JarResourceLocation [jarPath=D:\Program Files\Java\jdk1.8.0_101\jre\lib\jfxswt.jar], JarResourceLocation [jarPath=D:\Program Files\Java\jdk1.8.0_101\jre\lib\plugin.jar], JarResourceLocation [jarPath=F:\apache-maven-3.3.9\repository\jstl\jstl\1.2\jstl-1.2.jar], JarResourceLocation [jarPath=D:\Program Files\Java\jdk1.8.0_101\jre\lib\ext\sunpkcs11.jar], FileSystemResourceLocation [root=F:\ideaProject\newlook\target\classes], JarResourceLocation [jarPath=D:\Program Files\Java\jdk1.8.0_101\jre\lib\ext\sunec.jar], JarResourceLocation [jarPath=F:\apache-maven-3.3.9\repository\cn\enilu\tools\nutzwk-code-generator\1.1\nutzwk-code-generator-1.1.jar], JarResourceLocation [jarPath=F:\apache-maven-3.3.9\repository\org\nutz\nutz-web\1.r.57\nutz-web-1.r.57.jar], JarResourceLocation [jarPath=D:\Program Files\Java\jdk1.8.0_101\jre\lib\javaws.jar], JarResourceLocation [jarPath=F:\apache-maven-3.3.9\repository\org\slf4j\slf4j-api\1.6.6\slf4j-api-1.6.6.jar], JarResourceLocation [jarPath=F:\apache-maven-3.3.9\repository\commons-beanutils\commons-beanutils\1.8.3\commons-beanutils-1.8.3.jar], JarResourceLocation [jarPath=F:\apache-maven-3.3.9\repository\org\quartz-scheduler\quartz\2.2.1\quartz-2.2.1.jar], JarResourceLocation [jarPath=D:\Program Files\Java\jdk1.8.0_101\jre\lib\ext\zipfs.jar], JarResourceLocation [jarPath=F:\apache-maven-3.3.9\repository\org\eclipse\jetty\jetty-jsp\7.6.18.v20150929\jetty-jsp-7.6.18.v20150929.jar], JarResourceLocation [jarPath=D:\Program Files\Java\jdk1.8.0_101\jre\lib\management-agent.jar], JarResourceLocation [jarPath=D:\Program Files\Java\jdk1.8.0_101\lib\jconsole.jar], JarResourceLocation [jarPath=D:\Program Files\Java\jdk1.8.0_101\jre\lib\ext\localedata.jar], JarResourceLocation [jarPath=F:\apache-maven-3.3.9\repository\commons-logging\commons-logging\1.1.1\commons-logging-1.1.1.jar], JarResourceLocation [jarPath=F:\apache-maven-3.3.9\repository\log4j\log4j\1.2.17\log4j-1.2.17.jar], JarResourceLocation [jarPath=D:\Program Files\Java\jdk1.8.0_101\jre\lib\jce.jar], JarResourceLocation [jarPath=D:\Program Files\Java\jdk1.8.0_101\jre\lib\ext\access-bridge-64.jar], JarResourceLocation [jarPath=F:\apache-maven-3.3.9\repository\org\eclipse\jetty\orbit\javax.servlet.jsp.jstl\1.2.0.v201105211821\javax.servlet.jsp.jstl-1.2.0.v201105211821.jar], JarResourceLocation [jarPath=F:\apache-maven-3.3.9\repository\org\eclipse\jetty\orbit\javax.mail.glassfish\1.4.1.v201005082020\javax.mail.glassfish-1.4.1.v201005082020.jar], JarResourceLocation [jarPath=D:\Program Files\Java\jdk1.8.0_101\jre\lib\ext\jaccess.jar], JarResourceLocation [jarPath=D:\Program Files\Java\jdk1.8.0_101\jre\lib\ext\jfxrt.jar], JarResourceLocation [jarPath=E:\Program Files (x86)\JetBrains\IntelliJ IDEA 14.0.3\lib\idea_rt.jar], JarResourceLocation [jarPath=F:\apache-maven-3.3.9\repository\org\eclipse\jetty\orbit\org.apache.taglibs.standard.glassfish\1.2.0.v201112081803\org.apache.taglibs.standard.glassfish-1.2.0.v201112081803.jar], JarResourceLocation [jarPath=F:\apache-maven-3.3.9\repository\org\eclipse\jetty\orbit\com.sun.el\1.0.0.v201105211818\com.sun.el-1.0.0.v201105211818.jar], JarResourceLocation [jarPath=F:\apache-maven-3.3.9\repository\org\eclipse\jetty\aggregate\jetty-all-server\7.6.18.v20150929\jetty-all-server-7.6.18.v20150929.jar]]
2016-08-24 17:05:27,936 [main] DEBUG org.nutz.resource.Scans - Found 0 resource by src( /code/code.json ) , regex( ^(.+[.])(js|json)$ )
2016-08-24 17:05:28,031 [main] DEBUG org.nutz.castor.Castors - Using 94 castor for Castors
Disconnected from the target VM, address: '127.0.0.1:56421', transport: 'socket'
Exception in thread "main" java.lang.RuntimeException: folder or file like '^(.+[.])(js|json)$' no found in /code/code.json
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at org.nutz.lang.born.ConstructorBorning.born(ConstructorBorning.java:17)
    at org.nutz.lang.born.BornContext.doBorn(BornContext.java:60)
    at org.nutz.lang.Mirror.born(Mirror.java:990)
    at org.nutz.lang.Lang.makeThrow(Lang.java:121)
    at org.nutz.resource.Scans.loadResource(Scans.java:86)
    at org.nutz.ioc.loader.json.JsonLoader.<init>(JsonLoader.java:45)
    at cn.enilu.common.code.Generator.main(Generator.java:152)

Process finished with exit code 1`
生成的时候 报错了

**Comment by enilu** [comment]
@TonyYule  需要/code/code.json 这个配置文件了，去nutzwk-code-generator里面拷贝一份，即可。
